language: objective-c
before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild -workspace Breadcrumb.xcworkspace -sdk iphonesimulator -scheme Breadcrumb -configuration Debug test | xcpretty -c

